company_forum/urls.py
from django.conf.urls import url
from .views import company_forum,add_forum

urlpatterns = [
    url(r'^add-forum/(?P<id>.*)/$', add_forum, name='add-forum'),
    url(r'^(?P<id>.*)/$', company_forum, name='company-forum'),

]

company_jobs/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

konekin_enterprise/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import company_profile.urls as company_profile
import company_login.urls as company_login
import company_jobs.urls as company_jobs
import company_forum.urls as company_forum
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^company/login/', include(company_login, namespace='company_login')),
    url(r'^company/profile/', include(company_profile, namespace='company-profile')),
    url(r'^company/jobs/', include(company_jobs, namespace='company-jobs')),
    url(r'^company/forum/', include(company_forum, namespace='company-forum')),
    url(r'^$', RedirectView.as_view(url = '/company/login/', permanent = 'true'), name = 'company_login'),
]

company_forum/models.py
from django.db import models
from company_profile.models import CompanyAccount


# Create your models here.
class CompanyForum(models.Model):
    companyAccount = models.ForeignKey(CompanyAccount) #get the company you want here
    title = models.CharField(max_length=140)
    message = models.TextField()
    #kode_message = models.CharField("Kode Message", max_length=50)
    created_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.companyAccount.company_name


class Comment(models.Model):
    companyAccount = models.ForeignKey(CompanyAccount)
    companyForum = models.ForeignKey(CompanyForum)
    comment = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

company_forum/forms.py
from django import forms

class Forum_Form(forms.Form):
    error_messages = {
        'required': 'please fill this out...',
    }

    title_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Title here...'
    }

    post_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'form-control',
        'placeholder':'What jobs do you have? ...'
    }

    title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    post = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=post_attrs))

company_forum/views.py
from django.shortcuts import render
from company_profile.models import CompanyAccount
from django.http import HttpResponseRedirect
from .models import *
from .forms import *

from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

response = {}


def company_forum(request, id):
    print(id)
    print(id[-8:])

    count = CompanyAccount.objects.count()
    print(count)
    selected_company = CompanyAccount.objects.get(company_id=id[-8:])
    print(selected_company.company_id)

    forum = CompanyForum.objects.filter(companyAccount=selected_company)
    print(forum.count())

    response['sub_title'] = selected_company.company_name + ' Forum'
    response['id'] = id
    response['logo'] = selected_company.company_logo
    response['company'] = selected_company

    response['forum']: forum
    response['company_form'] = Forum_Form
    response['forum_list'] = forum

    forum_list = forum
    paginator = Paginator(forum_list, 5)
    page = request.GET.get('page', 1)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    response['forum_list'] = users
    response['is_logged_in'] = True
    html = "company_forum/company_forum.html"
    return render(request, html, response)


def add_forum(request, id):
    print(id)

    form = Forum_Form(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        selected_company = CompanyAccount.objects.get(company_id=id)
        print(selected_company)

        response['CompanyAccount'] = selected_company
        response['title'] = request.POST['title']
        response['message'] = request.POST['post']

        forumpost = CompanyForum(companyAccount=response['CompanyAccount'], title=response['title'],
                                 message=response['message'])  # model
        forumpost.save()

        # html = "company_forum/add_post.html"
        # return render(request,html,response)
        return HttpResponseRedirect('/company/forum/' + id + '/')


def paginate_page(page, data_list):
    paginator = Paginator(data_list, 5)

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = data.number - 1
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 10, so lets calculate where to slice the list
    start_index = index if index >= 5 else 0
    end_index = 5 if index < max_index - 5 else max_index
    # Get our new page range. In the latest versions of Django page_range returns
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data': data, 'page_range': page_range}
    return paginate_data

company_forum/templates/company_forum/add_post.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
    <style>
        .form-control {
            margin-top: 10px;
            margin-bottom: 5px;
        }

        .status {
            margin-top: 10px;
            margin-bottom: 30px;
        }
    </style>
    <div class="jumbotron jumbotron-fluid text-center"
         style="margin-bottom: 0px; margin-top: 0px; background-color: #FFFFFF">
        <div class="container">
            <img class="rounded-circle" src="{{ logo }}" alt="Perusahaan"
                 style="width:250px;height:240px;">
            <h1 class="display-3" style="font-family: Montserrat;padding-top: 20px; color: #2b7a78">Job Forum
                Discussion</h1>
            <h1 style="font-family:'Montserrat';text-align: center;color: #3aafa9">{{ company }}</h1>

        </div>
    </div>



    <div class="alert alert-danger text-center">
        <strong>Successfully added.</strong>
    </div>

    </div>
{% endblock %}

company_forum/templates/company_forum/company_forum.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
    <style>
        .form-control {
            margin-top: 10px;
            margin-bottom: 5px;
        }

        .status {
            margin-top: 10px;
            margin-bottom: 30px;
        }
    </style>
    <div class="jumbotron jumbotron-fluid text-center"
         style="margin-bottom: 0px; margin-top: 0px; background-color: #FFFFFF">
        <div class="container">
            <img class="rounded-circle" src="{{ logo }}" alt="Perusahaan"
                 style="width:250px;height:240px;">
            <h1 class="display-3" style="font-family: Montserrat;padding-top: 20px; color: #2b7a78">Job Forum Discussion</h1>
            <h1 style="font-family:'Montserrat';text-align: center;color: #3aafa9">{{ company }}</h1>

        </div>
    </div>


    <div class="container">
        <hr/>
        <section name="form">
            <h1 style="font-family:'Open Sans';text-align: center;padding-top: 20px;padding-bottom:30px; color: #3aafa9">Add Forum Post</h1>
            <form id="form" method="POST" action="{% url 'company-forum:add-forum' id %}">
                {% csrf_token %}
                {{ company_form }}
                <br>
                <button type="submit" class="btn btn-primary btn-lg btn-block"
                        style="background-color: #2b7a78;border-color: #3aafa9">Post
                </button>
            </form>
        </section>
        <hr/>
        <h1 style="font-family:'Open Sans';text-align: center; color: #3aafa9;padding-top: 15px;padding-bottom: 30px;">Job Forum</h1>

        {% if forum_list %}
            <div class="container">
            {% for data in forum_list %}

                <section name="update-status" id="update-status">
                    <div class="status">
                        <div class="media">
                            <div class="pull-left">
                                <img class="rounded-circle" src="{{ logo }}" alt="Perusahaan"
                                     style="width: 80px;padding-right: 8px">
                            </div>
                            <div class="media-body">
                                <h3 class="media-heading" style="color: #2b7a78">{{ data.title }}</h3>
                                <h6 style="color: #2b7a78">Posted on {{ data.created_date }}</h6>
                                {% comment %}<h6 style="color: #2b7a78">Post Id {{ data.companyAccount }}</h6>{% endcomment %}
                                <p style="color: #3aafa9">{{ data.message }}</p>
                                {% comment %}<div class="delete" data-id="{{ data.id }}">
                                <a href="{% url 'forum:clear' object_id=data.id %}"><img
                                        src="{% static 'image/bin.png' %}"
                                        style="width: 35px;height 35px; top: 10px;"></a>
                            </div>{% endcomment %}
                            </div>
                        </div>
                    </div>
                </section>

            {% endfor %}
            </div>
        {% else %}
            <div class="alert alert-danger text-center">
                <strong>You have no discussion.</strong> Please add one.
            </div>
        {% endif %}

        {% if forum_list.has_other_pages %}
            <div class="text-center">
                <ul class="pagination" style="text-align: center">
                    {% if forum_list.has_previous %}
                        <li><a href="?page={{ forum_list.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in forum_list.paginator.page_range %}
                        {% if forum_list.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if forum_list.has_next %}
                        <li><a href="?page={{ forum_list.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock %}