company_jobs/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

company_login/urls.py
from django.conf.urls import url
from .views import index,addCompanyData

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^company/data', addCompanyData, name= 'addCompanyData'),
]

konekin_enterprise/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import company_profile.urls as company_profile
import company_login.urls as company_login
import company_jobs.urls as company_jobs
import company_forum.urls as company_forum
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^company/login/', include(company_login, namespace='company_login')),
    url(r'^company/profile/', include(company_profile, namespace='company-profile')),
    url(r'^company/jobs/', include(company_jobs, namespace='company-jobs')),
    url(r'^company/forum/', include(company_forum, namespace='company-forum')),
    url(r'^$', RedirectView.as_view(url = '/company/login/', permanent = 'true'), name = 'company_login'),
]

company_login/models.py
from django.db import models

# Create your models here.

company_login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from company_profile.views import create_company_account
from django.views.decorators.csrf import csrf_exempt
import json


response = {}
def index(request):#pragma: no cover
    # response['author'] = "Claudio Yosafat"
    html = 'company_login/company_login.html'
    #html login
    response['is_logged_in'] = False
    response['is_company_login_html'] = True
    return render(request,html,response)


@csrf_exempt
def addCompanyData(request):#pragma: no cover
    print("masuk company data")
    if request.method == 'POST':
        print(request.POST)
        id = request.POST['data[id]']
        print(request.POST['data[name]'])
        company_id = id
        company_name = request.POST['data[name]']
        company_industries = request.POST['data[industries][values][0][name]']
        company_website=request.POST['data[websiteUrl]']
        company_headquarters=request.POST['data[locations][values][0][address][city]']
        company_year_founded=request.POST['data[foundedYear]']
        company_type=request.POST['data[companyType][name]']
        company_size=request.POST['data[employeeCountRange][name]'] + " employees"
        company_specialties=request.POST['data[specialties][values][]']
        company_description=request.POST['data[description]']
        company_logo=request.POST['data[squareLogoUrl]']
        listResponse = {'id' : id}
        create_company_account(company_id,company_name,company_industries,company_website,company_headquarters,company_year_founded,company_type,company_size,company_specialties,company_description,company_logo)
        return JsonResponse(listResponse)
    return HttpResponse()

company_login/templates/company_login/company_login.html
{% extends "layout/base.html" %} {% load staticfiles %} {% load static %} {% block content %}
<!-- sign in with linkedin button -->
<script type="IN/Login"></script>

<!-- <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 78z1y23eusl2sd
    authorize: true
    onLoad: onLinkedInLoad
    scope: r_basicprofile r_emailaddress rw_company_admin
</script> -->


<script type="text/javascript">

    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getCompanyProfileData);
    }


    function getCompanyProfileData() {
        var cpnyID = "13597930"
        IN.API.Raw("/companies/" + cpnyID + ":(id,name,ticker,description,company-type,founded-year,locations:(address),website-url,square-logo-url,specialties,industries,employee-count-range,logo-url)?format=json").method("GET").result(displayProfileData).error(onError);
    }


    function displayProfileData(data) {
        postData(data)
        console.log("INI DATA KITA AKHIRNYA");
        console.log(data);

        console.log(data.name);
        console.log("=================================");

        console.log("ini company type");
        console.log(data.companyType);

        console.log("=================================");

        console.log("Deskripsi");
        console.log(data.description);

        console.log("=================================");

        console.log("Ditemukan pada");
        console.log(data.foundedYear);

        console.log("=================================");

        console.log("Lokasi Perusahaan");
        //   console.log(data.locations.values[0]);
        console.log("Kota : " + data.locations.values[0].address.city);
        console.log("Kode Pos : " + data.locations.values[0].postalCode);
        console.log("Jalan : " + data.locations.values[0].street1);

        console.log("=================================");

        console.log("Konekin Specialties : ");
        console.log(data.specialties.values[0]);
        console.log(data.specialties.values[1]);
        console.log(data.specialties.values[2]);

        console.log("=================================");

        console.log("URL Konekin Logo :");
        console.log(data.squareLogoUrl);

        console.log("=================================");

        console.log("URL Konekin :");
        console.log(data.websiteUrl);

        console.log("==================================");

        console.log("Industries: ");
        console.log(data.industries.values[0].name);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log("eheheheh");
        console.log(data);
    }



    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to share content on LinkedIn
    function shareContent() {

        // Build the JSON payload containing the content to be shared
        var payload = {
            "comment": "Check out developer.linkedin.com! http://linkd.in/1FC2PyG",
            "visibility": {
                "code": "anyone"
            }
        };

        var cpnyID = 13597930;

        IN.API.Raw("/companies/" + cpnyID + "/shares?format=json")
            .method("POST")
            .body(JSON.stringify(payload))
            .result(onSuccess)
            .error(onError);
    }

</script>

<script>
    var postData = function (data) {
        $.ajax({
            method: "POST",
            url: '{% url "company_login:addCompanyData" %}',
            data: { data },
            success: function (data) {
                id = data['id'];
                window.open('/company/profile/' + id + '/', '_self');
                // window.open('https://konekin-enterprise.herokuapp.com/company/profile/' + id + '/', '_self')'' 
                // window.location.replace('localhost:8000/company/profile/' + id);
                console.log("BERHASIL");
        

            },
        })
    };
</script>


<!-- display profile info -->
<div id="profileData" style="display: none;">
    <p>
        <a href="javascript:void(0);" onclick="logout()">Logout</a>
    </p>
    <div id="picture"></div>
    <div class="info">
        <p id="name"></p>
        <p id="intro"></p>
        <p id="email"></p>
        <p id="location"></p>
        <p id="link"></p>
    </div>
</div>{% endblock %}